/* Generated By:JavaCC: Do not edit this line. PatinaParserTreeConstants.java Version 6.0_1 */
package parser;

public interface PatinaParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTDECLARATION = 1;
  public int JJTIMMUTABLEDECLARATION = 2;
  public int JJTMUTABLEDECLARATION = 3;
  public int JJTEXPRESSION = 4;
  public int JJTUNARYEXPRESSION = 5;
  public int JJTTYPE = 6;
  public int JJTASSIGNMENT = 7;


  public String[] jjtNodeName = {
    "Input",
    "Declaration",
    "ImmutableDeclaration",
    "MutableDeclaration",
    "Expression",
    "UnaryExpression",
    "Type",
    "Assignment",
  };
}
/* JavaCC - OriginalChecksum=244a7b977e07e571ceaf59b173c9af76 (do not edit this line) */
