/* Generated By:JavaCC: Do not edit this line. PatinaParserTreeConstants.java Version 6.0_1 */
package parser;

public interface PatinaParserTreeConstants
{
  public int JJTBOOLEANLITERAL = 0;
  public int JJTINPUT = 1;
  public int JJTSTATEMENT = 2;
  public int JJTEXPRESSION = 3;
  public int JJTDECLARATION = 4;
  public int JJTIMMUTABLEDECLARATION = 5;
  public int JJTMUTABLEDECLARATION = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTUNARYEXPRESSION = 8;
  public int JJTTYPE = 9;


  public String[] jjtNodeName = {
    "BooleanLiteral",
    "Input",
    "Statement",
    "Expression",
    "Declaration",
    "ImmutableDeclaration",
    "MutableDeclaration",
    "Assignment",
    "UnaryExpression",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=6b11444145a673b958bb4eff85007eda (do not edit this line) */
